services:
  app:
    image: app
    ports:
      - ${SERVER_PORT}:${SERVER_PORT}
    volumes:
      - /etc/letsencrypt:/etc/letsencrypt:ro
      - ./rideshare-frontend/build:/app/rideshare-frontend/build
    environment:
      SERVER_ENV: ${SERVER_ENV}
      SERVER_PORT: ${SERVER_PORT}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    depends_on:
      - db